import type { Restaurant } from "@/lib/types";

export const demoRestaurants: Restaurant[] = [
  {
    id: "demo-1",
    name: "소문난 국수집",
    category: "한식",
    area: "망원",
    address: "서울 마포구 월드컵로 12길 8",
    memo: "멸치 육수의 깊은 맛이 좋아서 비 오는 날이면 가장 먼저 생각나는 곳.",
    tags: ["국수", "한식"],
    hasVisited: false,
    imageUrl: null,
    imageUrls: [],
    imagePath: null,
    imagePaths: [],
    imageSourceUrl: null,
    imageCredit: null,
    imageCandidates: [],
    naverUrl: "https://map.naver.com/",
    latitude: 37.5564,
    longitude: 126.9014,
    sortOrder: 1,
    isVisible: true,
    createdAt: "2026-01-15T09:00:00.000Z",
    updatedAt: "2026-01-15T09:00:00.000Z",
  },
  {
    id: "demo-2",
    name: "오후의 작은 식탁",
    category: "양식",
    area: "성수",
    address: "서울 성동구 연무장길 21",
    memo: "요란하지 않은 파스타와 자연광이 좋은 창가 자리. 느긋한 점심에 잘 어울립니다.",
    tags: ["파스타", "양식"],
    hasVisited: false,
    imageUrl: null,
    imageUrls: [],
    imagePath: null,
    imagePaths: [],
    imageSourceUrl: null,
    imageCredit: null,
    imageCandidates: [],
    naverUrl: "https://map.naver.com/",
    latitude: 37.5446,
    longitude: 127.0559,
    sortOrder: 2,
    isVisible: true,
    createdAt: "2026-01-12T09:00:00.000Z",
    updatedAt: "2026-01-12T09:00:00.000Z",
  },
  {
    id: "demo-3",
    name: "저녁 7시의 커피",
    category: "카페",
    area: "연남",
    address: "서울 마포구 동진시장길 34",
    memo: "산미 있는 필터 커피와 조용한 음악. 하루를 정리하기 좋은 나만의 장소.",
    tags: ["카페", "디저트"],
    hasVisited: false,
    imageUrl: null,
    imageUrls: [],
    imagePath: null,
    imagePaths: [],
    imageSourceUrl: null,
    imageCredit: null,
    imageCandidates: [],
    naverUrl: "https://map.naver.com/",
    latitude: 37.5636,
    longitude: 126.9221,
    sortOrder: 3,
    isVisible: true,
    createdAt: "2026-01-08T09:00:00.000Z",
    updatedAt: "2026-01-08T09:00:00.000Z",
  },
];
